version: '3'

services:
  strapi:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: orchard-strapi
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - STRAPI_ADMIN_URL=${STRAPI_ADMIN_URL}
      - PUBLIC_URL=${PUBLIC_URL}
    volumes:
      - ./config:/usr/src/app/config
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
      - ./public/uploads:/usr/src/app/public/uploads
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orchard-strapi.rule=Host(`orchard-backend.deant.work`)"
      - "traefik.http.routers.orchard-strapi.entrypoints=websecure"
      - "traefik.http.routers.orchard-strapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.orchard-strapi.loadbalancer.server.port=1337"

volumes:
  orchard-data:

networks:
  proxy:
    external: true
